### ISSUE TITLE
Unexpected error on start

### ISSUE THREAD

**Issue by jsearl-plc** [StefanFanaru/PokerTime#3]
When clicking on the extension  to begin using it in our tenant, we get an "Authorizing User" message and then after a few seconds the extension redirects to an error screen that shows this:

![image](https://github.com/user-attachments/assets/b1fe883e-ac4f-43c1-8ec4-ab6f980c08a3)

This was working several weeks ago, but starting last week we started seeing this error.

**Comment by StefanFanaru** [comment]
Hey,
Thank you for raising this issue.
I was no longer monitoring this extension and I see that there is currently an issue with the  DNS. I’ll fix it this weekend.

Regards,
Stefan Fanaru
________________________________
From: jsearl-plc ***@***.***>
Sent: Friday, November 1, 2024 3:20:57 PM
To: StefanFanaru/PokerTime ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StefanFanaru/PokerTime] Unexpected error on start (Issue #3)


When clicking on the extension to begin using it in our tenant, we get an "Authorizing User" message and then after a few seconds the extension redirects to an error screen that shows this:

image.png (view on web)<https://github.com/user-attachments/assets/b1fe883e-ac4f-43c1-8ec4-ab6f980c08a3>

This was working several weeks ago, but starting last week we started seeing this error.

**Comment by jsearl-plc** [comment]
Any luck with the DNS issue?  I just checked and we are still getting the error from the extension within Azure DevOps.

Thanks,


[cid:ae5eb852-bcda-4793-901d-7c5478177ca0]

[cid:823f8681-7d29-444e-9746-e1b1cc24468e]<https://www.linkedin.com/company/parklawncorp>

[cid:e05864f5-6923-4818-aba1-9f1fe8497a90]<https://www.instagram.com/parklawncorp>

[cid:fd7745f2-337f-4031-ba80-7b0ef1e4512f]<https://www.facebook.com/ParkLawnCorp>

Jeremy Searl

DIRECTOR, APPLICATION / DATA DEVELOPMENT

[cid:1b533ab8-0181-4eb5-beb8-5a6cfb04ea04]

832.689.7774

[cid:b8ae01c2-f8f6-48c5-bf40-4a76de023d10]

***@***.******@***.***>

[cid:ef9042af-cdf7-453a-80c2-b06134273503]

parklawncorp.com<https://www.parklawncorp.com/>

***@***.***?anonymous&ep=bwmEmailSignature>               Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
________________________________
From: Stefan Fanaru ***@***.***>
Sent: Saturday, November 2, 2024 6:29 AM
To: StefanFanaru/PokerTime ***@***.***>
Cc: Jeremy Searl ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [StefanFanaru/PokerTime] Unexpected error on start (Issue #3)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This message has originated from an External Source. Please use proper judgement and caution when opening attachments, clicking links, or responding to this email.

**Comment by StefanFanaru** [comment]
Hey,
Sorry it took so long but I fixed it last night.
It should just be a matter of propagation now.

Regards,
Stefan Fanaru
________________________________

**Comment by jsearl-plc** [comment]
I'm still getting the error message as of 5 minutes ago.

Thanks,
Jeremy
________________________________
From: Stefan Fanaru ***@***.***>
Sent: Wednesday, November 6, 2024 12:36 AM
To: StefanFanaru/PokerTime ***@***.***>
Cc: Jeremy Searl ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [StefanFanaru/PokerTime] Unexpected error on start (Issue #3)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This message has originated from an External Source. Please use proper judgement and caution when opening attachments, clicking links, or responding to this email.

**Comment by agnieszka-puzio** [comment]
It doesn't work for me neither, same behaviour.

**Comment by StefanFanaru** [comment]
Again sorry, thought I fixed it but it still had a misconfiguration. I was away dealing with some personal stuff. 
It is up and running now.

**Comment by agnieszka-puzio** [comment]
No worries. I confirm it works now. Thank you!
